version: '3.4'
x-custom:
  shared_env: &shared_env
    PHP_IDE_CONFIG: 'serverName=docker'
services:
  web:
    image: nginx:latest
    privileged: true
    ports:
      - '80:80'
    env_file:
      - '.env'
    volumes:
      - ./:/app
      - ./environment/nginx/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./environment/php-7
    privileged: true
    links:
      - redis
      - mysqlsrv
    ports:
      - '2225:22'
      - '35732:35729'
      - '9879:9876'
      - '8082:8080'
    env_file:
      - '.env'
    environment:
      <<: *shared_env
    volumes:
      - ./:/app

  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "LAEfAvBcRwvcx27Q!"
      MYSQL_DATABASE: "motorcheck"
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - 6381:6379
    deploy:
      resources:
        limits:
          memory: 1g


